### ISSUE TITLE
Vaults not showing up on UI for new campaigns

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/milestonetracker-ui#32]
https://dapp.giveth.io/#/campaigns/6/vault

But the vault is there i swear

0xb826c5bfea40eb88ec540abc534ad66bb5d58315

**Comment by vsimetka** [comment]
I don't think it is an issue in the develop branch hence not an issue for me. We merge to master after review in barcelona. https://develop--milestonetracker.netlify.com/#/campaigns/6
