### ISSUE TITLE
Create new env.js

### ISSUE THREAD

**Issue by ojones** [Giveth/milestonetracker-ui#64]
Currently the env.js that we use for seed data comes from the giveth directory.  The addresses it assigns make it difficult to work with loaded seed data.

Create a new env.js with address configs that allow developers to edit milestones with the loaded seed data.

**Comment by rodney757** [comment]
okay so probably the best solution here is not to create a new env.js, but to choose the correct account in the code when sending a transaction.

new issue #70

**Comment by rodney757** [comment]
after looking into this a bit more, the above isn't correct. All that needs to happen is that we need to remove from givethdirectory/env.js the places where it sets the donor to a multisig as we don't support multisigs in the ui currently.

There is an issue with missing abis in the latest changes to the givethcampaign. Once that is fixed, I'll create env.js file w/o multisigs for the milestonetracker-ui

**Comment by rodney757** [comment]
added in #79
