### ISSUE TITLE
Pending milestones were hanging for too long

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/milestonetracker-ui#74]
Not sure what happened (should have take a screenshot) btu the pending milestoens were stuck in the pending column for a long time... even after multiple refreshes, went to the old dapp 10 min later and it was working so i went to the new dap to do a screen shot and then it was working....

**Comment by rodney757** [comment]
My guess is this has to do with the way the directory state is fetched and is fairly slow right now. This will be fixed in the new dapp.

If this happens again lmk if there are any errors on the console, which would allow me to determine if something went wrong
