### ISSUE TITLE
Fields that are displaying the addresses above need to change

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/milestonetracker-ui#85]
1. Add the Donor (the address that can accept proposed milestones)
2. Add the Recipient (The address that can propose milestones AND globally mark milestones complete)
3. Add the Arbitrator (Can arbitrate approve or reject)
4. Change the donation address to the token, I know it costs extra gas, but there is value in the clarity that the people donate to the same address of the token contract. 
5. Fix the missing `Escape Caller's Address` which should be renamed to `Escape Hatch Caller` 
6. Fix the missing `Escape Destination` which should be renamed to `Escape Hatch Destination`
7. Check that the donate button sends to the Token address and not the campaign (Again.. for clarity later when someone is wondering why they sent money there... they will see a token from there so that they can remember that they were donating to make the world a better place.)

**Comment by rodney757** [comment]
for 7 above, talk to jordi. He needs to modify the givethdirectory wrapper to send to the token and not the controller.

the rest is done in #87
